name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'
          cache-dependency-path: 'requirements/*.txt'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            adduser base-files bash bash-completion binutils command-not-found coreutils cpp-11 cron debconf distro-info-data e2fsprogs fuse3 gcc gcc-11 gettext-base hdparm keyutils libattr1:amd64 libaudit-common libbinutils:amd64 libc-bin libc6-dev:amd64 libc6:amd64 libctf0:amd64 libgcc-11-dev:amd64 libgmp10:amd64 libisl23:amd64 libmagic1:amd64 libmecab2:amd64 libmpc3:amd64 libmpfr6:amd64 libpam-runtime libpython3.9-dev:amd64 libpython3.9-minimal:amd64 libpython3.9-stdlib:amd64 libsensors-config libtirpc-common libyaml-0-2:amd64 libyaml-dev:amd64 libzstd1:amd64 linux-libc-dev:amd64 locales login logrotate lsb-release ltrace mailcap man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3-zope.interface python3.9-distutils python3.9-minimal rsyslog screen sudo tar tzdata ucf unixodbc-common usb-modeswitch walinuxagent wget

      - name: Install tox
        run: |
          pip install tox==4.28.0

      - name: Upgrade Python tooling
        run: |
          pip install --upgrade pip setuptools virtualenv wheel

      - name: Upgrade tox
        run: |
          pip install --upgrade tox

      - name: Run tox for Python 3.9
        run: |
          tox run -f py$(echo '3.9' | tr -d . | cut -f 1 -d '-')

      - name: Run tox environments
        run: |
          tox -e base,dist,docs
